# Generated by Django 3.2.4 on 2021-06-20 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reclamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente'),
        ),
    ]
