# Generated by Django 3.2.4 on 2021-06-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reclamo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.colaborador'),
        ),
    ]
